package com.example.offline.repository.domain.org

import androidx.room.Entity

internal const val ORG_TABLE_NAME = "orgs"

@Entity(tableName = ORG_TABLE_NAME)
data class OrgEntity(
    val orgId: String,
    val tenantId: String,
    val posTerminalId: String,
    val roleId: String,
    val deviceToken: String,
    val userNameGetToken: String,
    val passwordGetToken: String,
    val userId: String,
    val tenantName: String,
    val roleCode: String,
    val orgName: String,
    val routeFunction: String
) {
    // Primary key is auto-generated by Room
    var cid: String = "%s:%s".format(orgId, tenantId)
}
