package com.example.offline.repository.domain.org

import androidx.room.Entity
import androidx.room.PrimaryKey

internal const val ORG_TABLE_NAME = "orgs"

@Entity(tableName = ORG_TABLE_NAME)
data class OrgEntity(
    val tenantId: String,
    val name: String,
    val orgId: Int? = null,
    val posTerminalId: Int? = null,
    val roleId: Int? = null,
    val deviceToken: String? = null,
    val userNameGetToken: String? = null,
    val passwordGetToken: String? = null,
    val userId: Int? = null,
    val tenantName: String? = null,
    val roleCode: String? = null,
    val orgName: String? = null,
    val routeFunction: String? = null
) {
    // Primary key is auto-generated by Room
    @PrimaryKey
    var cid: String = "%s:%s".format(orgId, tenantId)
}
