package com.example.offline.repository.domain.order

import androidx.room.Entity
import androidx.room.PrimaryKey

internal const val ORDER_TABLE_NAME = "orders"

@Entity(tableName = ORDER_TABLE_NAME)
data class OrderEntity(
    val customerId: String,
    val totalAmount: Double,
    val status: String
) {
    // Primary key is auto-generated by Room
    @PrimaryKey
    var cid: String = "%s:%s".format(customerId, status)
}